style>
  .bg{
    background-image: url("https://images.theconversation.com/files/393210/original/file-20210401-13-z6rl6z.jpg?ixlib=rb-4.1.0&rect=0%2C292%2C3008%2C1504&q=45&auto=format&w=1356&h=668&fit=crop");
  }
</style>
<body class="bg">
<h2 style="color:white"> Câu lạc bộ Thể thao trương THPT Lịch Hội Thượng</h2>
<img src="https://lh6.googleusercontent.com/proxy/NW7ieqjeJ1XoN_GzVhX-sXnUzS437CGh35DJ0S7jJFU_aKecIS1UqJlM9SUNVgXiDXKgK_hUy0SgYVy_Sb51WuRfjsU4kcISRuO8jURwiDA" alt="Hoạt động CLB thể thao"width="400" height="300">
</body>
